CREATE TABLE items
(
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(1000) NOT NULL,
    created BIGINT NOT NULL,
    modified BIGINT NOT NULL,
    priority SMALLINT NOT NULL CHECK (priority >= 0 AND priority <= 100),
    description CLOB NOT NULL
);

CREATE TABLE files
(
    id INTEGER NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(1000) NOT NULL,
    type VARCHAR(1000) NOT NULL,
    size BIGINT NOT NULL
);

CREATE TABLE itemfiles
(
    item_id INTEGER NOT NULL REFERENCES items(id),
    file_id INTEGER NOT NULL PRIMARY KEY REFERENCES files(id)
);
