CREATE TABLE items
(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(1000) NOT NULL,
    created BIGINT NOT NULL,
    modified BIGINT NOT NULL,
    priority SMALLINT NOT NULL,
    description CLOB NOT NULL
);

CREATE TABLE files
(
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
    name VARCHAR(1000) NOT NULL,
    type VARCHAR(1000) NOT NULL,
    size BIGINT NOT NULL
);

CREATE TABLE itemfiles
(
    item INTEGER NOT NULL,
    file INTEGER NOT NULL
);
